### ISSUE TITLE
Client crash on using banner rage

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [FortyTwoFortyTwo/Randomizer#11]
Had Soda Popper and Battalion's Backup as Sniper, right before raising banner and switching weapon to Soda Popper, client crash happened. Could not remember what melee weapon i had, but likely irrelevant.

**Comment by Djrulz0826** [comment]
Issue appears to be related to sniper, tested every class with battalion's backup and even a heavy w/ soda popper & battalion's. 
Every class functions properly (save for the phlog[or any rage weapon] + banner, but that's another issue), except sniper who crashes the client and server regardless of banner type.
Related video:
https://youtu.be/8PUOE_q8Ses (may take >30 minutes after commenting to upload due to slow internet)
