### ISSUE TITLE
x10 weapon support/attributes/template?

### ISSUE THREAD

**Issue by MoleMad** [FortyTwoFortyTwo/Randomizer#63]
I'm not sure if this is beyond the scope of this project, but I was wondering how possible/difficult would it be to make a branch or template of this plugin where all default tf2 weapons are given x10 attributes? For example, the stock knife having x10 melee speed or direct hit having x10 projectile speed?

**Comment by FortyTwoFortyTwo** [comment]
Someone could theoretically make a separate 10x weapons plugin to load with randomizer plugin together without needing to modify randomizer plugin itself (there might already be 10x plugin somewhere that would work?). I'm happy to take PR on randomizer fixes/changes that would indirectly make 10x plugin work.

But otherwise I'm not interested to update randomizer plugin that would single-handily make 10x work, and I'm not interested to make separate 10x plugin myself.

**Comment by MoleMad** [comment]
Sorry I should of phrased this better. Is there an easy way to simply edit the item attributes of the vanilla weapons instead of adding custom weapons? Or would it be possible to implement something like it?
